{
  "default": true,
  "MD003": { 
    "style": "atx" 
  },
  "MD007": { 
    "indent": 4 
  },
  "MD013": { 
    "line_length": 120,
    "heading_line_length": 100,
    "code_blocks": false,
    "tables": false
   },
  "MD024": { 
    "siblings_only": true 
  },
  "MD033": false,
  "no-hard-tabs": false,
  "whitespace": false
}